spring:
  application:
    name: ${APP_NAME:auth-service}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
    show-sql: ${SHOW_SQL:true}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}

  redis:
    url: ${REDIS_URL}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

logging:
  level:
    org:
      springframework:
        security: ${SECURITY_LOG_LEVEL:DEBUG}

springdoc:
  swagger-ui:
    tags-sorter: ${SWAGGER_TAG_SORTER:alpha}
  api-docs:
    packages-to-scan: ${API_PACKAGES:com.message.auth_service.controllers}

app:
  static:
    value: ${STATIC_VALUE}
